[DM-34800] Add SASL configuration to ts_salkafka
lsst-ts/ts_salkafka pull request #31
Opened 2022-07-05 20:28 UTC by afausti

In Sasquatch Kafka access to Kafka brokers is now authenticated via SASL (Simple Authentication and Security Layer). This PR adds SASL authentication to the `ts_salkafka` client using the SASL_PLAINTEXT protocol and SCRAM-SHA-512 method. 

`ts_salkafa` is going to use the `ts-salkafka` Kafka user, and the password will be provided via a k8s secret. This requires a change on the `ts_salkafka` Helm chart which will be implemented in another PR.

2022-07-06 18:56 UTC, r-owen requested changes
This looks like a very useful addition. However, I _think_ the error handling could use a bit of work. My apologies if I am wrong.

2022-07-06 18:56 UTC, r-owen commented on python/lsst/ts/salkafka/component_producer_set.py
> +        )
When you parse this in `amain`, please check that both or neither of these new arguments is submitted and call `parser.error(msg)` (or possibly raise argparse.ArgumentError) on error, in order to give nicer output if the user messes up.

2022-07-06 18:56 UTC, r-owen commented on python/lsst/ts/salkafka/kafka_producer_factory.py
> +        else:
Please reject the case that only one of the username or password are given.

2022-07-06 18:56 UTC, r-owen commented on python/lsst/ts/salkafka/kafka_producer_factory.py
> +        else:
Please reject the case that only one of the username or password are given

2022-07-06 18:56 UTC, r-owen commented on python/lsst/ts/salkafka/component_producer_set.py
> +            help="Kafka password for SASL authentication.",
In all of this review I will assume that a user must either provide both of these arguments or neither. If that is false then many of my comments are irrelevant. So, assuming that....

Please expand the help to say that both or neither must be provided.

2022-07-07 01:16 UTC, r-owen approved these changes
I have further requests for adding error handling that I hope you will consider before merging.

In general I strongly prefer to make all classes reject invalid arguments. I feel that gives the best feedback, and it can be especially helpful if code is changed in the future.

2022-07-07 01:16 UTC, r-owen commented on python/lsst/ts/salkafka/component_producer_set.py
> +            parser.error("You must specify --username.")
Thank you for this nice addition. I gently suggest expanding the text a bit, e.g.:
```
"You must specify --password if you specify --username"
```
and vice-versa for the second one.

2022-07-07 01:16 UTC, r-owen commented on python/lsst/ts/salkafka/kafka_producer_factory.py
> +        if self.config.sasl_plain_username:
What does AdminClient do if username or password are None? Unless it presents a really clear error message, please check here.

2022-07-07 01:16 UTC, r-owen commented on python/lsst/ts/salkafka/kafka_producer_factory.py
> +        if self.config.sasl_plain_username:
Here again I suggest checking that both or neither are None before constructing the AIOKafkaProducer.

(A simple function that asserts that both or neither are None might reduce repetition.)

2022-07-07 16:02 UTC, mareuter commented
The version history also needs to be updated.

2022-07-07 23:16 UTC, merged